-- R6 validation fixture f1: single correlated sample agrees with UTC by coincidence
-- Ground truth: all API traffic (role fx_api, Sydney override) is Sydney; the ONLY booking+proposal pair was written by a bypassing tool session (role postgres, server default UTC) on 2026-05-12
-- Current state left behind: server default UTC; the API role's override was RESET afterwards
-- Generated by run_r6_fixtures.py; load with psql (-v ON_ERROR_STOP=1) on schema.sql.
-- A timestamptz literal assigned to a `timestamp` column is converted in the session
-- TimeZone, exactly like the columns' DEFAULT now() at that instant.

DO $$BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'fx_api') THEN CREATE ROLE fx_api LOGIN; END IF; END$$;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO fx_api;
ALTER ROLE fx_api IN DATABASE r6_f1 SET timezone = 'Australia/Sydney';
\connect - fx_api
RESET TIME ZONE;
DO $$BEGIN IF current_setting('TimeZone') <> 'Australia/Sydney' THEN RAISE EXCEPTION 'writer zone is %', current_setting('TimeZone'); END IF; END$$;  -- writer: role fx_api, session TimeZone Australia/Sydney
INSERT INTO messages VALUES ('b4058655-3dba-5142-b4cb-35f1618da556', 'dfeb4d6e-8e54-5600-a688-a97600b239ee', '43dd28bb-4166-5d79-9c0a-85fcb2732ce7', 'fixture', TIMESTAMPTZ '2026-02-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('3ef516ee-5b64-5a0e-b69f-5c8a1494777f', 'dfa83038-7ee2-585d-8b49-b471bdcd9728', 'ExponentPushToken[3ef516ee]', 'ios', TIMESTAMPTZ '2026-02-05 08:00:00+00');
INSERT INTO messages VALUES ('557f260a-b62c-5552-acf4-ffcd56e2715e', '9d5d0a05-e522-5ef9-a9a7-0abc845b76cc', 'b6d8f311-d604-5f75-8dae-8e7aa474d34a', 'fixture', TIMESTAMPTZ '2026-02-10 12:00:00+00');
INSERT INTO blocks VALUES ('7e3e1608-2b3f-5bff-a091-9d5f80299202', '813b17b9-d2cd-5595-bd33-8026ff30ae97', 'f6438f3d-2de1-5bb4-8b1d-2033df394cc0', TIMESTAMPTZ '2026-02-12 05:00:00+00');
INSERT INTO reports VALUES ('2e8ca268-2400-5cc9-8c8b-cacfdf132a2d', '091ed651-8f46-5fb0-9639-6133f6e751f5', 'eefd7524-e28c-5f86-9ac6-781336cfb5f3', 'other', TIMESTAMPTZ '2026-02-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('401f9af7-5956-51b3-979d-4a279c19e9d6', '5fda7acf-cd96-51ea-8468-f474fe26618b', 'primary', TIMESTAMPTZ '2026-02-20 07:00:00+00');
INSERT INTO messages VALUES ('1d2b5e43-f834-5987-ad2b-676d72ec4aef', 'db7214ea-61f2-5a38-a423-3de4b41ddd9f', 'f19ab931-ea92-5e33-a0ae-19bbd545d137', 'fixture', TIMESTAMPTZ '2026-02-24 21:45:00+00');
INSERT INTO messages VALUES ('5531522e-c909-5b12-b687-6d52b3a1cc26', '662cbf8b-34ed-578a-aa25-26b21629d3ea', '89d9fc87-7f7c-5596-8b3d-83cd10666482', 'fixture', TIMESTAMPTZ '2026-03-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('ca3f2cd3-174b-533b-bc71-9fd30677a1a4', 'd1a6863c-86e7-559b-a51e-10c4eaaba887', 'ExponentPushToken[ca3f2cd3]', 'ios', TIMESTAMPTZ '2026-03-05 08:00:00+00');
INSERT INTO messages VALUES ('93ff2f35-144a-5b8c-a908-59bc12e0c5d7', '2831eee4-9d1c-5476-ae24-175b3c589739', '0d496cfc-a089-57fe-a2d5-4fc68da1ea35', 'fixture', TIMESTAMPTZ '2026-03-10 12:00:00+00');
INSERT INTO blocks VALUES ('20857e2f-3945-50be-9eb0-7e28547be1db', 'e09bfee2-d89a-5f04-ab25-bf2342c88f0a', '0b08d264-a516-5d4b-9453-466250a68bcc', TIMESTAMPTZ '2026-03-12 05:00:00+00');
INSERT INTO reports VALUES ('4971e043-8422-5dab-ad59-9a422ab29e8e', 'f96d5798-5034-5714-9af2-5b0ca5aa434d', '42fdbb99-920e-54a5-8ec9-f99cf24158f3', 'other', TIMESTAMPTZ '2026-03-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('317ce1c0-9d66-565b-aa50-27453621057b', 'ded9a554-4824-5cc7-9da9-74bb10a05046', 'primary', TIMESTAMPTZ '2026-03-20 07:00:00+00');
INSERT INTO messages VALUES ('042915ca-c623-53db-8f25-7d1bd83cac6e', 'a4428c2a-f49f-56b7-87e9-5556ded75507', '9d766378-0535-59e7-935a-193fdaab2011', 'fixture', TIMESTAMPTZ '2026-03-24 21:45:00+00');
INSERT INTO messages VALUES ('094ee9e4-1f32-5e76-9b16-51ea83dcccf7', 'fdd640d0-bfec-52d8-83c8-310fb971a627', '24b57630-e610-5479-80fa-3d3423825029', 'fixture', TIMESTAMPTZ '2026-04-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('3ea648ce-0edb-5598-b68b-c13964fa8c8f', '5a724b38-0afb-561f-9656-79d04763c277', 'ExponentPushToken[3ea648ce]', 'ios', TIMESTAMPTZ '2026-04-05 08:00:00+00');
INSERT INTO messages VALUES ('2f33446f-aad8-5ff8-bf46-679ffcc39711', '9734602f-9fe4-54c9-bb88-1db84ac8f686', '8f8da586-acd4-54bd-b791-785987a2374e', 'fixture', TIMESTAMPTZ '2026-04-10 12:00:00+00');
INSERT INTO blocks VALUES ('20edc018-34dc-5406-857c-c65ea676dea7', 'a634f9d8-5aed-5bfa-af93-80f21982b0d1', '15c20083-b05a-5e9f-bdaf-e594c7421331', TIMESTAMPTZ '2026-04-12 05:00:00+00');
INSERT INTO reports VALUES ('a55d16c2-337c-58c3-9beb-a3ccab8b455a', 'e3766357-954b-516e-b2c1-7d953cdd17e0', '88ac2a0b-310a-58ed-a5fa-0e9529896363', 'other', TIMESTAMPTZ '2026-04-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('e3869676-cc3c-5dfe-b018-67b1aff151ac', '83d2fdd5-8ace-5e34-a35c-437de5b096ad', 'primary', TIMESTAMPTZ '2026-04-20 07:00:00+00');
INSERT INTO messages VALUES ('8bb01a20-21a1-58ee-a4f7-72441f436485', 'f1ce5be1-3423-5d95-ac1a-b02be13357db', '87b2ed26-b844-57d7-af88-65c68b13ed34', 'fixture', TIMESTAMPTZ '2026-04-24 21:45:00+00');
INSERT INTO messages VALUES ('52414064-715e-5c92-83f5-57436b9d39d7', 'e64fea43-09e5-5041-a312-3d5c96aeb494', 'a4af845e-6088-5fdd-a0a5-548c5e3c3931', 'fixture', TIMESTAMPTZ '2026-05-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('d0a8862e-a09e-52be-a1e0-32ca04f3b517', '74052d6f-c9c3-5be3-b49a-9583c31ecf5c', 'ExponentPushToken[d0a8862e]', 'ios', TIMESTAMPTZ '2026-05-05 08:00:00+00');
INSERT INTO messages VALUES ('be857518-e2c3-5195-adba-11422f043237', '7d226e66-7cef-5aef-a111-8b02198e4578', '51e30ff9-5e60-5d14-952e-b20c191c3682', 'fixture', TIMESTAMPTZ '2026-05-10 12:00:00+00');
INSERT INTO blocks VALUES ('73f2b82f-7ed4-5ea3-8070-88c2718eabda', '26f604d4-b6ff-5c33-b503-89945fd767a8', '50c23dba-f9f9-5d12-b6a2-50c2789612d1', TIMESTAMPTZ '2026-05-12 05:00:00+00');
INSERT INTO reports VALUES ('645e5648-b9a7-5f81-a50e-be5e5dc75ee0', 'fad600e8-c53f-5db4-a384-9b83e39d8415', 'f4da9275-c77b-5501-89a7-dc8c8f1c30f4', 'other', TIMESTAMPTZ '2026-05-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('0b8b1091-d9d2-5eb5-847e-27843bcac38d', '85e1272a-7585-5674-a400-49d1ca895e6d', 'primary', TIMESTAMPTZ '2026-05-20 07:00:00+00');
INSERT INTO messages VALUES ('02a01ade-3aa7-58c0-8e28-2f667c107c16', '14590c47-1096-5797-850c-54f3ee6e6090', 'b4a5e839-2389-5ad7-83d5-8aa5e7424813', 'fixture', TIMESTAMPTZ '2026-05-24 21:45:00+00');
INSERT INTO messages VALUES ('fb3cb754-9559-53b2-87c3-0b2a3683c364', '2e909888-7da8-54f3-be3b-4edfcc178c01', 'aa6fb0a1-6648-579a-9f50-191b156319c2', 'fixture', TIMESTAMPTZ '2026-06-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('eba4090b-c5ff-54b1-a126-8fcc72ea5145', '5dacbb22-eede-539f-b48f-6669304b9595', 'ExponentPushToken[eba4090b]', 'ios', TIMESTAMPTZ '2026-06-05 08:00:00+00');
INSERT INTO messages VALUES ('ef874617-b14a-5deb-af22-f9ac28b360c3', 'd5c6613d-74b0-5810-ade6-385c67a662a8', '0bfa23a2-c52d-5244-996c-4bbc679d0e93', 'fixture', TIMESTAMPTZ '2026-06-10 12:00:00+00');
INSERT INTO blocks VALUES ('b14e866a-0ac2-5f7b-a10e-7351ea0ba5df', '12cde982-0cc6-5f4a-aff5-9f7ac3e36a54', '84078886-036c-592d-9f5a-ccb4328f293c', TIMESTAMPTZ '2026-06-12 05:00:00+00');
INSERT INTO reports VALUES ('15ca1c71-82d5-5cd0-9e68-fc77cfbca41b', '081f2b26-6cb5-5eb9-b696-059de545f0a9', '3c57e9b2-4b28-513b-8d17-201ec46eeea2', 'other', TIMESTAMPTZ '2026-06-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('4aad51d1-c591-5248-b965-e515baa4b037', 'c93f725b-4737-5958-b9ed-1e49562b35b1', 'primary', TIMESTAMPTZ '2026-06-20 07:00:00+00');
INSERT INTO messages VALUES ('a6f41f65-9511-52e5-9733-f47672453763', '4a459643-eabc-5f78-ac78-181e4fe697a1', 'c1bd5b69-c5be-55af-a26d-8e3908e8b771', 'fixture', TIMESTAMPTZ '2026-06-24 21:45:00+00');
INSERT INTO messages VALUES ('dae3356a-2534-590f-be44-05d9dfbb0b7f', '4d916ee6-c791-56e0-8d7c-51beb0f47b60', 'ab8ccafe-f07b-5db6-aebe-973596d69c7b', 'fixture', TIMESTAMPTZ '2026-07-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('1be01146-4b2c-57f5-9b06-0a139748219d', 'afdc2c58-227d-5979-8259-fa0b4181c07b', 'ExponentPushToken[1be01146]', 'ios', TIMESTAMPTZ '2026-07-05 08:00:00+00');
INSERT INTO messages VALUES ('adf4f121-7143-56ce-9b9c-f840f04bdd39', 'e2471b6e-411f-50d6-9435-66da73e15389', '3116fbd0-08f4-5aeb-8f07-51eaa93c245d', 'fixture', TIMESTAMPTZ '2026-07-10 12:00:00+00');
INSERT INTO blocks VALUES ('b6da8e90-5f3e-5f0a-8736-bec1d644d15b', '41b57f5a-e723-5a2d-8615-1e00c9bcd891', '2f0fb7bc-c066-5919-b26e-b92edc9b93a5', TIMESTAMPTZ '2026-07-12 05:00:00+00');
INSERT INTO reports VALUES ('3d899811-c2ac-5e09-bc82-8431ab95fe4a', '32019261-34d1-5085-a9f2-eaae391686ad', 'bb983248-b779-5122-8fb2-0e8d1252614f', 'other', TIMESTAMPTZ '2026-07-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('d7ec190b-f409-5cad-9674-b3044a9c4ea7', 'b8b57302-0de3-519c-935d-e9e27fb1ec5f', 'primary', TIMESTAMPTZ '2026-07-20 07:00:00+00');
INSERT INTO messages VALUES ('5f700497-bd77-5a7f-8c25-63f2376d9ace', '4a3ca734-82ff-541a-a6ea-28f7b6ec18c2', 'c7d8d431-5720-5b9b-bfcb-8f4a4df00e8d', 'fixture', TIMESTAMPTZ '2026-07-24 21:45:00+00');
INSERT INTO messages VALUES ('e55913dd-f808-5c3a-81e1-2ab120298301', '581eab72-6ab0-5236-89bc-bad9e93fbdf4', '34506f63-c7e0-5ca3-8d53-b26f056cf684', 'fixture', TIMESTAMPTZ '2026-08-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('23817b5d-1f8c-5115-af22-ad78f3114e0e', 'e9478732-1ecd-535b-8091-783de6ffd035', 'ExponentPushToken[23817b5d]', 'ios', TIMESTAMPTZ '2026-08-05 08:00:00+00');
INSERT INTO messages VALUES ('3120c712-576f-52cb-811b-1e5b4a2c9e70', '9de7565c-534c-5831-8de1-2c687d69718e', 'f9d4e202-5f7c-5120-bb45-e657e4a9df5b', 'fixture', TIMESTAMPTZ '2026-08-10 12:00:00+00');
INSERT INTO blocks VALUES ('c570cce4-ca16-53d3-961f-fb5028fa6369', 'c4e47e3c-6ddf-5374-8271-683879de3329', '6bd71d28-aae1-5a8e-a358-9feed85b180a', TIMESTAMPTZ '2026-08-12 05:00:00+00');
INSERT INTO reports VALUES ('aa1eb284-ca90-583d-a834-f342d22504df', '94f2d3a0-85a7-505d-8833-a67d06a86498', '39b4ba3a-b4e1-5a66-9d11-cc4445877b8f', 'other', TIMESTAMPTZ '2026-08-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('5f5948f0-784b-5bb7-8272-d1a67602d820', '29f2ce51-12f1-52a7-bbea-7777213d84f8', 'primary', TIMESTAMPTZ '2026-08-20 07:00:00+00');
INSERT INTO messages VALUES ('64ae23e3-0803-5d50-b295-a04af4a8e0d1', '756a173c-dad7-5ecb-a124-6a5fb9645b9a', '86445a04-bf60-5f4d-a383-a4d294d6bff4', 'fixture', TIMESTAMPTZ '2026-08-24 21:45:00+00');
INSERT INTO messages VALUES ('fadf0ee0-0e80-54d4-b10d-c3d781e52e3c', '1c191db1-d802-571e-a503-70c6bf264536', '83fd9d8c-81b1-5007-a3c1-d6c4f2537fde', 'fixture', TIMESTAMPTZ '2026-09-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('c54e40d4-abe4-5572-98ac-45c84eb7ee88', '64c0b498-ad95-5255-86c4-88f09d3b1466', 'ExponentPushToken[c54e40d4]', 'ios', TIMESTAMPTZ '2026-09-05 08:00:00+00');
INSERT INTO messages VALUES ('da6fa21b-b7f8-5cdb-a332-53009294fc97', '0e1f4e62-5f26-5ae1-9665-f0eaacc36dc9', 'a89625b0-382f-5cc2-8440-ba70db0e2416', 'fixture', TIMESTAMPTZ '2026-09-10 12:00:00+00');
INSERT INTO blocks VALUES ('af51f6ab-6964-5cd8-8dcd-4e5b070d45e5', 'e2ac4126-d25b-5920-b442-499e75b122b7', '8913233f-05c5-5b85-9bd9-3380f9d8164a', TIMESTAMPTZ '2026-09-12 05:00:00+00');
INSERT INTO reports VALUES ('0986227d-acdd-534a-ae42-430d2f9a8469', 'fed94712-ec8a-52c0-89fb-059a87bc5075', '2d5dfa9d-3bd8-5ab3-89fe-ca338929ef02', 'other', TIMESTAMPTZ '2026-09-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('be2c48e3-6e86-5bec-aa80-577cb08de679', '3595191f-85cc-57db-9e43-dc4b55c9c98b', 'primary', TIMESTAMPTZ '2026-09-20 07:00:00+00');
INSERT INTO messages VALUES ('afe64c7c-3e4c-5b07-b4a8-55a430b09ab7', 'fd7d04ed-81f7-53e0-9c9e-857fa21d402f', '9d9bc49f-d2fb-5f17-ad32-eda7f90f3ec4', 'fixture', TIMESTAMPTZ '2026-09-24 21:45:00+00');
\connect - postgres
RESET TIME ZONE;
DO $$BEGIN IF current_setting('TimeZone') <> 'UTC' THEN RAISE EXCEPTION 'writer zone is %', current_setting('TimeZone'); END IF; END$$;  -- writer: role postgres, session TimeZone UTC
INSERT INTO bookings (id, match_id, proposer_id, partner_id, sport, starts_at, ends_at, created_at, updated_at) VALUES ('95db0860-7e84-5c56-87f9-00b624d09108', 'b360a243-ab55-5c8b-89cc-516246360131', '1671ed8e-60c1-505e-9a94-e7b8ac26899e', '24409c11-4d6b-59c6-81dc-af611acd44eb', 'tennis', TIMESTAMPTZ '2026-05-14 02:00:00+00', TIMESTAMPTZ '2026-05-14 03:00:00+00', TIMESTAMPTZ '2026-05-12 02:00:00+00', TIMESTAMPTZ '2026-05-12 02:00:00+00');
INSERT INTO notification_events (id, user_id, booking_id, notification_type, title, body, scheduled_at, created_at) VALUES ('13ca302e-0628-5a89-a07f-643df740f06a', '24409c11-4d6b-59c6-81dc-af611acd44eb', '95db0860-7e84-5c56-87f9-00b624d09108', 'proposal_received', 'New session proposal', 'fixture', TIMESTAMPTZ '2026-05-12 02:00:00.037+00', TIMESTAMPTZ '2026-05-12 02:00:00+00');
ALTER ROLE fx_api IN DATABASE r6_f1 RESET timezone;
