-- R6 validation fixture f2: single correlated sample in an AEST month (Sydney and fixed +10 indistinguishable)
-- Ground truth: Sydney throughout (Jan..Sep, AEDT rows Jan-Mar); one proposal only, 2026-06-10T04:00Z (+10)
-- Current state left behind: server default UTC, no overrides
-- Generated by run_r6_fixtures.py; load with psql (-v ON_ERROR_STOP=1) on schema.sql.
-- A timestamptz literal assigned to a `timestamp` column is converted in the session
-- TimeZone, exactly like the columns' DEFAULT now() at that instant.

SET TIME ZONE 'Australia/Sydney';
DO $$BEGIN IF current_setting('TimeZone') <> 'Australia/Sydney' THEN RAISE EXCEPTION 'writer zone is %', current_setting('TimeZone'); END IF; END$$;  -- writer: role postgres, session TimeZone Australia/Sydney
INSERT INTO messages VALUES ('4608a0e8-f1e8-5011-bf80-90e3d16af18f', '14d7d1b3-8a57-5c8d-8ced-9f226909ffc6', 'b9c651f2-222b-51ef-8aa0-b7f746f65403', 'fixture', TIMESTAMPTZ '2026-01-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('0adc3856-bb47-5b0d-91b8-230e1a2f5068', '1e9431db-7cd0-5a5b-8e38-e40bf03beb6d', 'ExponentPushToken[0adc3856]', 'ios', TIMESTAMPTZ '2026-01-05 08:00:00+00');
INSERT INTO messages VALUES ('06cd711e-ce5d-5d41-a9b6-fb99fcfe4170', '3f4e76bf-5849-5316-93cc-85353f364109', 'b068558d-06bc-5fed-addf-9e300e8afed6', 'fixture', TIMESTAMPTZ '2026-01-10 12:00:00+00');
INSERT INTO blocks VALUES ('d73b1289-56b3-5d96-ade3-c6a74a44deb8', 'ea0f0048-f2c8-5219-bc66-848488bba9b1', '8bd2820d-d654-5317-a08a-52774f3220fe', TIMESTAMPTZ '2026-01-12 05:00:00+00');
INSERT INTO reports VALUES ('47d814d7-1568-5793-bf14-13ca57f4fcd8', '5d296209-164a-517b-b82d-0b5ad11d6bde', '2020758b-32e1-5171-82ad-7a89dac75304', 'other', TIMESTAMPTZ '2026-01-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('a0c1a823-a310-55be-a1c0-eee32492cce1', '49076f1e-8467-5ab6-951d-8ffda0d52fe6', 'primary', TIMESTAMPTZ '2026-01-20 07:00:00+00');
INSERT INTO messages VALUES ('4a9dd421-7893-58a3-b76e-a624b0b634ce', 'a6d8ddf0-a06d-5ce8-9090-3c658d6f9777', '3bd55853-c874-5adb-b15a-1608d52b2433', 'fixture', TIMESTAMPTZ '2026-01-24 21:45:00+00');
INSERT INTO messages VALUES ('0627a87a-4bd7-5eed-ab1e-bfa52181ed33', '953eb3fe-73c9-54f1-b080-f6e321562a1a', '4521aea7-0b68-5646-a63b-c43f722f8845', 'fixture', TIMESTAMPTZ '2026-02-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('0a083285-f4a9-5ba7-834c-e1111a343879', '1845e317-fea6-5ab8-84e6-61233d620aef', 'ExponentPushToken[0a083285]', 'ios', TIMESTAMPTZ '2026-02-05 08:00:00+00');
INSERT INTO messages VALUES ('2f3eaa09-df80-5c2a-8322-31ae6dcb1902', '2e01dad6-fec9-5ba0-85e0-154ad7e27b3a', '87724f4f-b666-575f-aba9-594003017b28', 'fixture', TIMESTAMPTZ '2026-02-10 12:00:00+00');
INSERT INTO blocks VALUES ('9a94e5f5-28a9-5e8c-a27d-c818134ba016', '97fa59bf-1ec5-5c80-a945-b08c006199ed', '341640a3-2f7f-5ce8-8c67-f637fdd65a1d', TIMESTAMPTZ '2026-02-12 05:00:00+00');
INSERT INTO reports VALUES ('81326994-2762-54b6-b247-80274fcdda27', '67b43815-db8d-569b-b1b9-bc1d8d88c4d5', 'b8c87a3f-6249-5005-a98b-b71aa96a1f30', 'other', TIMESTAMPTZ '2026-02-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('147eafbc-3e0f-5651-8eda-93abb69f5b70', 'a0b52dbc-e40d-5c63-9c9d-02f815d3cc87', 'primary', TIMESTAMPTZ '2026-02-20 07:00:00+00');
INSERT INTO messages VALUES ('35f01268-011e-5177-83b9-5c5d31ad70e7', 'b26a49c0-1c0f-5113-b13e-08c7f0f978f1', '57b1a9af-703b-512a-b394-98dffde9e558', 'fixture', TIMESTAMPTZ '2026-02-24 21:45:00+00');
INSERT INTO messages VALUES ('6a457fa2-1a17-5866-b004-f2e42cacfa71', 'dd2bbf77-c23f-5ff7-bb77-eafd54d5138a', '38192494-f135-5ba1-ab28-f4f64b7083af', 'fixture', TIMESTAMPTZ '2026-03-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('140135f5-b8fa-5923-a644-e99638ed6f35', 'a56437c2-a137-52f0-923e-e81790c639cc', 'ExponentPushToken[140135f5]', 'ios', TIMESTAMPTZ '2026-03-05 08:00:00+00');
INSERT INTO messages VALUES ('d96f0bf5-81b0-576d-8cc5-d9034e6cd2fb', 'f8c28e47-3072-534d-8586-f5e397dd29c8', '708a6bec-0d90-5aec-913f-35df8b3a393e', 'fixture', TIMESTAMPTZ '2026-03-10 12:00:00+00');
INSERT INTO blocks VALUES ('620d1b0b-1b17-53e0-beec-838d0d27dcdb', 'd3050924-8dc3-5602-91f2-bd4ee3f3aefb', '6389c138-2b3b-5837-ba22-65fee4ef574d', TIMESTAMPTZ '2026-03-12 05:00:00+00');
INSERT INTO reports VALUES ('efa9fe6a-dd29-5aec-aa0a-058a4253b27a', 'cf2fa220-552b-59bf-b4a8-af67c0b7c691', '509edba5-9999-50d8-8987-21b283b8574f', 'other', TIMESTAMPTZ '2026-03-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('d35ae531-c388-535e-a12e-a2d4e3ef6c29', '542b93a6-d5d5-5f40-8fe8-df95b160329d', 'primary', TIMESTAMPTZ '2026-03-20 07:00:00+00');
INSERT INTO messages VALUES ('0b7ab300-7cdf-5ac9-9d63-fb493e2c4121', '2da403a0-6e1e-559a-8ea6-0b3bc7c50ac8', 'd0cf9588-e81b-5e50-8998-c6266e54d0c9', 'fixture', TIMESTAMPTZ '2026-03-24 21:45:00+00');
INSERT INTO messages VALUES ('0fa465c2-7fc9-5b32-a48e-f707c29b8b99', '069faaa1-846a-5146-bc7e-f01883465f1e', '0226f057-c8c1-597a-9888-0b1b917ec2ed', 'fixture', TIMESTAMPTZ '2026-04-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('fb1260bf-56ec-5a42-b7a1-d7148424d1e0', '34ea54ab-a58a-55c1-8447-9eb27ff219ed', 'ExponentPushToken[fb1260bf]', 'ios', TIMESTAMPTZ '2026-04-05 08:00:00+00');
INSERT INTO messages VALUES ('a4eb6b3d-db40-59e3-8b34-d656eb5fefc5', '6826dfbf-94d5-5283-94e2-f2667b571cb0', 'c48916b3-ccc1-555d-87fe-72b9f64f6a56', 'fixture', TIMESTAMPTZ '2026-04-10 12:00:00+00');
INSERT INTO blocks VALUES ('04469641-3184-5b5c-917d-6e5c7b91b690', 'c154f556-51d8-5d05-8e86-b551726df7ff', '38be1beb-efb6-596d-af99-2e3946b9d9f4', TIMESTAMPTZ '2026-04-12 05:00:00+00');
INSERT INTO reports VALUES ('958f01d6-3b9f-5180-bea8-ca5c0c70b26b', 'fbede5fb-44cb-5a7b-93ac-d1b26fd50fe6', '1c547a1f-d754-579c-86b4-9543f076b2a0', 'other', TIMESTAMPTZ '2026-04-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('18d40601-97d0-500e-806c-8594e2fb8a63', 'f0aeb3a5-20dc-5bc0-8bce-433cc7e96b36', 'primary', TIMESTAMPTZ '2026-04-20 07:00:00+00');
INSERT INTO messages VALUES ('2bec9170-642e-51e3-9264-8b02b583fc0e', 'cb0830ad-dd61-5d16-8731-3d1aae187fb6', '0687deee-26f6-5941-aa8b-adc3d7c794b9', 'fixture', TIMESTAMPTZ '2026-04-24 21:45:00+00');
INSERT INTO messages VALUES ('97f30e61-4e46-5563-b601-9ee62e9fcb9c', 'aca061ee-e31a-5b2c-95b3-5497085619a5', '25e9cbad-fa06-5353-a2bc-9eef6dfb3b57', 'fixture', TIMESTAMPTZ '2026-05-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('c1bac93f-b880-52cc-b0b8-7957c28be1ba', 'f1218559-053a-5f20-a0aa-4ca5bbd253f3', 'ExponentPushToken[c1bac93f]', 'ios', TIMESTAMPTZ '2026-05-05 08:00:00+00');
INSERT INTO messages VALUES ('2461f9f3-c95e-52d3-9895-08fc18168da0', '2b9f1e99-5eeb-5b6d-90db-58991f827cf2', '5c7cddd3-5bce-5501-beae-a5278c5323cd', 'fixture', TIMESTAMPTZ '2026-05-10 12:00:00+00');
INSERT INTO blocks VALUES ('d9b39ee3-3335-5379-aa0a-7c6e0f4568f6', 'a4ae5e42-8379-53d8-b1af-1d3030366b33', '1136d773-4a1b-5ba8-b5c0-63bd26c452dc', TIMESTAMPTZ '2026-05-12 05:00:00+00');
INSERT INTO reports VALUES ('1fae0f9c-3285-5532-a791-da993fb006a1', '1452345d-efe8-5f5c-bb37-c1281a4f1e1e', '6ed23e55-c6d5-5b73-90d2-09e66ffd3fbc', 'other', TIMESTAMPTZ '2026-05-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('221d1781-4d3a-5005-81eb-50693c646306', 'e73cb23b-f2a5-577f-97c1-978401c4d919', 'primary', TIMESTAMPTZ '2026-05-20 07:00:00+00');
INSERT INTO messages VALUES ('fd6df8f3-28ed-5c5e-bb04-3aa1d4c35ed5', 'ab9d50a4-7b54-5e58-bfc1-cec444d4fbeb', '645878c9-59f7-5bd3-8133-7123cedd74f9', 'fixture', TIMESTAMPTZ '2026-05-24 21:45:00+00');
INSERT INTO messages VALUES ('dc3c2a29-77a9-5320-b736-12e318c28c6c', 'bc9df2dc-44ed-53cd-a5e1-ce9dae45cc46', 'fe3c3610-e3d0-5b64-bb9f-76eed630dc85', 'fixture', TIMESTAMPTZ '2026-06-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('7cc80576-dcb2-5786-93f0-31694d3f51a3', '118b3a85-f88b-52cc-9954-1d056c9950e1', 'ExponentPushToken[7cc80576]', 'ios', TIMESTAMPTZ '2026-06-05 08:00:00+00');
INSERT INTO messages VALUES ('9d367335-68e4-564f-bec7-ac1ccb01e259', 'c0f60ddb-7f06-59c3-b461-52dc74f5cb4c', 'a25ce535-9afe-5245-9e0c-84a0854d5123', 'fixture', TIMESTAMPTZ '2026-06-10 12:00:00+00');
INSERT INTO blocks VALUES ('8527a3ae-ecb5-54ef-ad25-6b95238432c1', '1cd6e82a-91b7-5838-b509-d0d0974065e4', 'da5ea9a4-b3c5-5288-9836-f72274492891', TIMESTAMPTZ '2026-06-12 05:00:00+00');
INSERT INTO reports VALUES ('6ea0bfee-b04f-5f8c-9de3-7afa93a71718', '7193e21d-e3da-5e6d-8650-3315ce9a99a3', '20fd9d64-4785-5dae-852a-39780b3d5162', 'other', TIMESTAMPTZ '2026-06-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('897bea60-6190-508b-b50e-9718d3e13499', 'a3950776-3eeb-5a31-9284-139a43c6b9f7', 'primary', TIMESTAMPTZ '2026-06-20 07:00:00+00');
INSERT INTO messages VALUES ('ae9d127c-c84d-53f3-8b82-d568a2e0c10a', '271356bc-a7d9-58b2-a5d2-1ab2797600b0', '8c607d6a-c666-5c78-a9c4-7bfcfb352295', 'fixture', TIMESTAMPTZ '2026-06-24 21:45:00+00');
INSERT INTO messages VALUES ('7d5e813c-896e-53a8-9120-6483a7e274ff', 'c1c63bc1-cfcb-5c49-9048-20d464a39689', '2bf36509-d61b-5607-a47a-9c78408428c7', 'fixture', TIMESTAMPTZ '2026-07-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('4ec5b7d2-5d1a-5174-b0ff-7763e2c89a75', 'e4afc71d-e606-5fca-9f7c-53f74f740139', 'ExponentPushToken[4ec5b7d2]', 'ios', TIMESTAMPTZ '2026-07-05 08:00:00+00');
INSERT INTO messages VALUES ('475bfa1a-96c0-5436-ac1a-c881d58a4365', '85f3e1f6-2ae6-5da1-9e0e-567737aa1be1', 'e11a32bb-718e-5214-84c3-2114e478ddce', 'fixture', TIMESTAMPTZ '2026-07-10 12:00:00+00');
INSERT INTO blocks VALUES ('e78c9a82-548c-5033-86eb-35c18c01da36', '545f51c6-0362-5570-854c-0fca5a0682d7', 'f68a3881-e233-5a05-a539-85c42802d15e', TIMESTAMPTZ '2026-07-12 05:00:00+00');
INSERT INTO reports VALUES ('d5ebceda-0ad1-5b8e-817b-7dc657d28327', '7a842459-618e-5198-89da-d30bb404a856', '38b17e9e-d8c1-5f1a-8868-6a79ab066a20', 'other', TIMESTAMPTZ '2026-07-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('61c902a2-582b-5ff6-83b2-f3c12cdce4ef', '9071d241-ca1e-5b1a-9265-e4c23873e9e3', 'primary', TIMESTAMPTZ '2026-07-20 07:00:00+00');
INSERT INTO messages VALUES ('01d7f1cb-0a60-52ac-886f-b5a2bea1c4a5', '8e4f6db5-0654-53c3-938e-44edd120c916', '57bc36e1-311d-5f25-aebc-a38da5f54588', 'fixture', TIMESTAMPTZ '2026-07-24 21:45:00+00');
INSERT INTO messages VALUES ('b028fe10-77af-5460-91dc-5aa1a712046c', 'f7e1d358-c93d-5713-9a49-e6d3a21a164c', '4b18c8f9-d2c7-565f-abec-f152cf199d8c', 'fixture', TIMESTAMPTZ '2026-08-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('226984e8-da77-57eb-a8ff-5d09c3e4cebf', '9d1e6cdd-59c9-5ea7-b46c-0b161f0fece9', 'ExponentPushToken[226984e8]', 'ios', TIMESTAMPTZ '2026-08-05 08:00:00+00');
INSERT INTO messages VALUES ('c8ec0e37-1dc2-5e03-9d77-2ff4a645033a', '5a25e7ed-3182-5804-95f2-4e02b8beb18c', '28dab281-f827-50e8-928f-1655d6f4aa05', 'fixture', TIMESTAMPTZ '2026-08-10 12:00:00+00');
INSERT INTO blocks VALUES ('c6819221-2bbb-59a6-a131-a9f50157b5f9', 'f0fd7256-6300-52f7-9853-954082b78bc5', '58511989-d174-5195-b731-9c38c7b8edac', TIMESTAMPTZ '2026-08-12 05:00:00+00');
INSERT INTO reports VALUES ('e7b15737-6de4-59af-8ff1-a4edd57e2735', '70173dd2-3795-56dd-afec-db678b9d616a', 'e8c92894-e340-5503-b547-3d34e74d5cd3', 'other', TIMESTAMPTZ '2026-08-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('f3cf7629-c099-52b5-9c64-e03e133157ab', '683b5b01-af2b-5076-b533-b017ac1c1b64', 'primary', TIMESTAMPTZ '2026-08-20 07:00:00+00');
INSERT INTO messages VALUES ('5fdc9487-8f0f-5e23-93ef-93de4b720cef', '6f20703d-1886-5bef-a487-eeea02954992', 'faa6e3a2-c750-536b-8915-e8a493890f9f', 'fixture', TIMESTAMPTZ '2026-08-24 21:45:00+00');
INSERT INTO messages VALUES ('30627366-6b5b-5c41-9f67-31158c89de92', 'e1203bec-8c2d-55c5-8742-1ce825d6df79', '22dc275c-e4f2-5d6b-b943-e55bcffcd5cb', 'fixture', TIMESTAMPTZ '2026-09-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('00ea3a10-7c8d-52fa-9144-8069f16fbe28', '192e8393-a275-5105-9df4-6b631b23fd43', 'ExponentPushToken[00ea3a10]', 'ios', TIMESTAMPTZ '2026-09-05 08:00:00+00');
INSERT INTO messages VALUES ('b69b11f0-80a5-567e-aa2b-399bcb3b3418', 'f4b25a15-fffb-5935-9bf2-a8bce0a2cea7', '9c9a95c4-abea-5ba9-9821-ae37c1e55d9c', 'fixture', TIMESTAMPTZ '2026-09-10 12:00:00+00');
INSERT INTO blocks VALUES ('1af57087-c6aa-5e11-8382-a4bb8ce4e8c9', '5509db4a-0666-59df-9b53-262034b57739', '10eacfe8-4889-5e68-ae4d-8450d2e6c5fd', TIMESTAMPTZ '2026-09-12 05:00:00+00');
INSERT INTO reports VALUES ('daa23f38-0c5b-53c5-9510-dd2be02d2bf7', 'b515def4-9bc1-5aa1-861b-15ab39780484', '5c358029-9070-5777-8a77-57af278fbb77', 'other', TIMESTAMPTZ '2026-09-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('8efa8ec9-2d46-578a-9db6-9f5467167656', '2e8286ad-9f11-5122-936a-1d68d4e3ae7b', 'primary', TIMESTAMPTZ '2026-09-20 07:00:00+00');
INSERT INTO messages VALUES ('56e2d74d-2d03-5052-8c00-0fe3867ba538', '0040951a-00ee-5f6b-8af3-bb041fdbee92', '4654a367-a97c-5699-8f13-6dd62dc42db8', 'fixture', TIMESTAMPTZ '2026-09-24 21:45:00+00');
INSERT INTO bookings (id, match_id, proposer_id, partner_id, sport, starts_at, ends_at, created_at, updated_at) VALUES ('9d20d79b-9a7d-5a86-a564-5e8c5c4b05aa', '99a6350e-8ad7-563e-a568-123e9b25b814', '66ff92bd-daf1-5915-bbae-92525cf151e7', 'e56b4bc6-060d-50fe-8909-0273e6fb32b7', 'tennis', TIMESTAMPTZ '2026-06-12 04:00:00+00', TIMESTAMPTZ '2026-06-12 05:00:00+00', TIMESTAMPTZ '2026-06-10 04:00:00+00', TIMESTAMPTZ '2026-06-10 04:00:00+00');
INSERT INTO notification_events (id, user_id, booking_id, notification_type, title, body, scheduled_at, created_at) VALUES ('5ceb221b-4a1a-5b40-be3d-9f8ee87e0a77', 'e56b4bc6-060d-50fe-8909-0273e6fb32b7', '9d20d79b-9a7d-5a86-a564-5e8c5c4b05aa', 'proposal_received', 'New session proposal', 'fixture', TIMESTAMPTZ '2026-06-10 04:00:00.037+00', TIMESTAMPTZ '2026-06-10 04:00:00+00');
