-- R6 validation fixture g: no correlated sample at all
-- Ground truth: Sydney history via a since-removed role override; no booking has a proposal notification
-- Current state left behind: server default UTC; override RESET, so step 1 shows UTC and no overrides
-- Generated by run_r6_fixtures.py; load with psql (-v ON_ERROR_STOP=1) on schema.sql.
-- A timestamptz literal assigned to a `timestamp` column is converted in the session
-- TimeZone, exactly like the columns' DEFAULT now() at that instant.

DO $$BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'fx_api') THEN CREATE ROLE fx_api LOGIN; END IF; END$$;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO fx_api;
ALTER ROLE fx_api IN DATABASE r6_g SET timezone = 'Australia/Sydney';
\connect - fx_api
RESET TIME ZONE;
DO $$BEGIN IF current_setting('TimeZone') <> 'Australia/Sydney' THEN RAISE EXCEPTION 'writer zone is %', current_setting('TimeZone'); END IF; END$$;  -- writer: role fx_api, session TimeZone Australia/Sydney
INSERT INTO messages VALUES ('eee59b83-0807-56ba-84d9-1dc7b972a8a5', 'd7cdff5d-dd11-536e-928e-88c835893595', '7bcb102c-8b39-5cea-804b-b81bfd1468f8', 'fixture', TIMESTAMPTZ '2026-02-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('399fc952-5747-5d33-864c-8e28cb4d9ac2', '55014c3b-c2da-57f0-ad79-c18091b592f7', 'ExponentPushToken[399fc952]', 'ios', TIMESTAMPTZ '2026-02-05 08:00:00+00');
INSERT INTO messages VALUES ('cb20afd2-c568-5f2a-9247-185447d3e55a', '2af06f84-2d0b-512a-ad79-c298518b0b77', '0740ebed-ee9b-54b6-9967-d21d639a9567', 'fixture', TIMESTAMPTZ '2026-02-10 12:00:00+00');
INSERT INTO blocks VALUES ('4e9c0c99-0b56-551c-b180-20592138c4b5', '8d2ee4ab-ee33-570b-aa67-90c785a29fc8', 'cbac197f-8a89-5cfb-8067-993f3fea0214', TIMESTAMPTZ '2026-02-12 05:00:00+00');
INSERT INTO reports VALUES ('dc795956-9aa6-56fc-ad23-2e01d2bd5d6f', '318f71c0-a9f0-53fa-bb4e-0436efdd5a19', '580a03d3-15b9-5760-9bc9-3e2f8202fd9d', 'other', TIMESTAMPTZ '2026-02-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('5b191628-1c87-5f50-96c1-959bbe953f67', '8dceef56-d987-56f7-b0be-d96af9650ccb', 'primary', TIMESTAMPTZ '2026-02-20 07:00:00+00');
INSERT INTO messages VALUES ('d0509137-66a9-5e1d-9198-718ab471b736', '003dd9e0-8e11-5141-86ed-63215b2be799', '3bb1894c-5daf-58a1-865e-906068ed1e0f', 'fixture', TIMESTAMPTZ '2026-02-24 21:45:00+00');
INSERT INTO messages VALUES ('4ddec23a-f9c5-5c14-9ea4-23e4c4152f1b', '4721048c-7e53-5bb9-80a9-752f2a528a19', '7b262a8b-a552-5ed7-9fc8-585495d6bc38', 'fixture', TIMESTAMPTZ '2026-03-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('d0fd2817-b660-57a0-8fc7-8c606e0294a6', '5ac5d98b-2f64-5345-88ca-c2784f4d7af6', 'ExponentPushToken[d0fd2817]', 'ios', TIMESTAMPTZ '2026-03-05 08:00:00+00');
INSERT INTO messages VALUES ('61667512-b286-5218-a877-b9e229847c27', '7be603a7-c208-579a-8637-58e32c2178b7', '9329524c-400b-538c-a070-117207754ef6', 'fixture', TIMESTAMPTZ '2026-03-10 12:00:00+00');
INSERT INTO blocks VALUES ('69ac9dbf-c487-5b3b-b7f0-809038b7299b', '735bf817-b0d2-5b1a-b8c1-f0a7faf13411', 'dc8f1c76-917f-5025-b8d7-e98bbac88fb3', TIMESTAMPTZ '2026-03-12 05:00:00+00');
INSERT INTO reports VALUES ('f1fbc05a-4093-584b-a4ca-8b480aef01d2', '1d85fb44-5c85-5d96-91f0-2dfb456e07b7', '1a137dd4-3086-502a-ac55-fc15a8d58fa9', 'other', TIMESTAMPTZ '2026-03-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('f4393833-3919-513b-b310-91d2474a2fce', '15da8fa8-fcac-566a-b96d-5e53922463ab', 'primary', TIMESTAMPTZ '2026-03-20 07:00:00+00');
INSERT INTO messages VALUES ('051a6fcb-dca1-58e2-b02b-5c6b6cf56818', '27358707-8172-53c3-a91a-f63b130e7773', 'fe8f4c4a-43ea-5e16-b7b6-397e8423cc23', 'fixture', TIMESTAMPTZ '2026-03-24 21:45:00+00');
INSERT INTO messages VALUES ('466beae6-414c-5e23-a5f4-f5f8cbca58e7', '22854a34-d88a-5a89-a717-54da395d69e3', '68faf39f-3b46-5518-9c96-4f3887c37ba5', 'fixture', TIMESTAMPTZ '2026-04-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('ec46e9e2-9b87-5fb9-a286-13054fe0c3b4', '64d7bacc-5bde-5c1b-a572-4f9d222b1b41', 'ExponentPushToken[ec46e9e2]', 'ios', TIMESTAMPTZ '2026-04-05 08:00:00+00');
INSERT INTO messages VALUES ('104f4f73-842f-5261-9909-0fe9b468ed26', '4afbfe35-df30-59af-a3d5-48c00a6a0306', '00130520-39b2-5025-9beb-9cbb28b1122f', 'fixture', TIMESTAMPTZ '2026-04-10 12:00:00+00');
INSERT INTO blocks VALUES ('200a9afa-9e36-5337-9255-630af6075ee5', 'cb5a0af5-9be8-5d86-86ae-e229f0c44bac', 'bc2c7c73-f095-5639-9597-5705654cb53b', TIMESTAMPTZ '2026-04-12 05:00:00+00');
INSERT INTO reports VALUES ('f5154b1f-110e-5b15-a26f-c69527988fec', 'c9aca760-faa8-5950-ba76-dc83ea10f7a5', '168524ec-4bba-529f-bbbd-b4fb9b815738', 'other', TIMESTAMPTZ '2026-04-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('ee604d9c-bec1-5f9f-919e-6fc4bb59c54c', '6ec7ffd9-a3ba-559e-b3e6-a937d2fd4713', 'primary', TIMESTAMPTZ '2026-04-20 07:00:00+00');
INSERT INTO messages VALUES ('cc9f6cb8-b16a-5699-b3c3-eb371d995c2b', '7f3ff4fd-41bf-548f-ae96-35ed292a3734', 'f3c50de1-ceeb-5e02-b6b6-22fe3f99d9f9', 'fixture', TIMESTAMPTZ '2026-04-24 21:45:00+00');
INSERT INTO messages VALUES ('25f5038d-4dbe-587d-8f8d-8b810761f0c6', 'bb4381cd-1145-50ff-bd00-c381b5292722', '62291146-39d3-5898-bba0-21d21956e575', 'fixture', TIMESTAMPTZ '2026-05-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('207ec299-4b1e-5388-8865-8557c45dd42d', 'deafc5b6-ca7b-5938-b379-68d41d55d8e1', 'ExponentPushToken[207ec299]', 'ios', TIMESTAMPTZ '2026-05-05 08:00:00+00');
INSERT INTO messages VALUES ('8aa100aa-bd4d-53d2-a01e-c18db23a3230', 'a1ae98f5-c36c-581a-ad30-02e0267e5778', '00eaeb71-3d04-5319-81a3-4b849ac50abc', 'fixture', TIMESTAMPTZ '2026-05-10 12:00:00+00');
INSERT INTO blocks VALUES ('ded42fb0-614e-5ba7-8571-6e4ed745d979', '3e2c993b-daaa-507e-bc6b-75941315d2b1', '72f1308f-737a-5424-9cb0-de428f8e3368', TIMESTAMPTZ '2026-05-12 05:00:00+00');
INSERT INTO reports VALUES ('951946da-b9b6-5444-a211-6ea54d91586a', '8e447580-049a-5182-babf-f19256919ada', '4070b6a8-035d-57f4-a0d1-5559ed62daee', 'other', TIMESTAMPTZ '2026-05-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('e49c3769-bc63-59a2-a920-7c842f81227d', '7968728f-8cc1-5cbe-aa68-eaed895b0094', 'primary', TIMESTAMPTZ '2026-05-20 07:00:00+00');
INSERT INTO messages VALUES ('4ea08f81-5104-5da2-97bc-006c18270c9c', 'bb0d1591-9755-5c1c-b55a-697f0fe2f4f4', '919cbc87-c4eb-53a7-b170-3ef454720866', 'fixture', TIMESTAMPTZ '2026-05-24 21:45:00+00');
INSERT INTO messages VALUES ('c9f7918d-bfc8-5ff2-8464-e10c2b04dde3', 'fd70d82f-9a1a-53ac-ac20-fef7bf13e620', 'af363ac5-0985-570e-8f4f-ae67bdd0bfc6', 'fixture', TIMESTAMPTZ '2026-06-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('166505c8-027a-513d-b49d-3540b366a9a3', '80872f4d-c4ee-5b04-819f-f48142c81d22', 'ExponentPushToken[166505c8]', 'ios', TIMESTAMPTZ '2026-06-05 08:00:00+00');
INSERT INTO messages VALUES ('8b039e8e-1b12-5b93-8e8c-e3dffbfefed9', '5f4bb2dd-10ac-5924-ab8f-c0ccb8d6de95', '4bd118a4-f777-57bf-a4f8-c34f16d33bbd', 'fixture', TIMESTAMPTZ '2026-06-10 12:00:00+00');
INSERT INTO blocks VALUES ('35060825-1d65-5202-b2ef-1beab412ce0d', '9ba71c65-0a86-5557-919a-60bfad837ce9', '4a764d73-f95b-5946-bbe8-5e75ed8c6809', TIMESTAMPTZ '2026-06-12 05:00:00+00');
INSERT INTO reports VALUES ('91f2bc6d-3ec8-55bd-9102-be9fbcb5ebc7', 'f9b4b8b1-3f03-5fb0-9285-f1598321ca21', '625b3891-cbaa-5a01-aae0-3c9addb3e8ab', 'other', TIMESTAMPTZ '2026-06-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('5916a733-ffaa-5d15-92a7-cb017c53b68a', 'f7776e26-a180-5358-994b-a1ed1623ef8f', 'primary', TIMESTAMPTZ '2026-06-20 07:00:00+00');
INSERT INTO messages VALUES ('a4d5750f-98d7-539d-9ac9-c5e5f74398e4', 'ba83176c-bb49-554b-bf5e-96ab01bee8ff', 'b99e166e-fee6-543a-983e-ce2e6553e5fa', 'fixture', TIMESTAMPTZ '2026-06-24 21:45:00+00');
INSERT INTO messages VALUES ('b8ead151-bb0d-5cfc-83a8-b0016ce214ee', '9c489811-a6de-5103-9317-582e30efd790', '31009814-1ab5-5bcc-9566-a10569c6544d', 'fixture', TIMESTAMPTZ '2026-07-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('ccc464f6-40d3-5951-81f3-3fa1188ebeed', '34a6fa02-dc19-5d3f-9aff-1b0088264922', 'ExponentPushToken[ccc464f6]', 'ios', TIMESTAMPTZ '2026-07-05 08:00:00+00');
INSERT INTO messages VALUES ('44b8a699-32ed-54e8-9c65-aaf8ebf51c29', '3026880b-d861-5149-b643-e3513d4de4e8', '1c1a8994-9fa6-59f5-b68f-b40a59f0b710', 'fixture', TIMESTAMPTZ '2026-07-10 12:00:00+00');
INSERT INTO blocks VALUES ('94ac45f9-bd97-5b41-a277-46ede30ec7ee', 'd145cf7c-b4d6-5512-aefb-5f708646e685', 'a5dea4e4-ab52-5920-b1f5-8f7839b4ea9e', TIMESTAMPTZ '2026-07-12 05:00:00+00');
INSERT INTO reports VALUES ('5710ac8e-7907-55b2-8c2d-ba6a67b90b3a', '2cb067fc-a66c-5632-9c77-43526ed3b281', '085707a9-3cdc-53b8-a6e6-81eabff9c02c', 'other', TIMESTAMPTZ '2026-07-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('2a52883a-19c0-5c7e-856c-3905c63b3ac3', 'ec64e999-4339-5d5d-b4ba-2582dc33c441', 'primary', TIMESTAMPTZ '2026-07-20 07:00:00+00');
INSERT INTO messages VALUES ('f08f1be8-5e3a-5fdf-a749-767ebdf7b5d2', '6bcd24dc-aae2-5eba-bdae-dafc7757a607', '0fbbc947-3574-5b9f-9946-fd2fe2e40386', 'fixture', TIMESTAMPTZ '2026-07-24 21:45:00+00');
INSERT INTO messages VALUES ('001c10a4-fd3a-56d8-b1ed-549a8b748867', '321ce3d6-9e54-5148-962b-cd0ffbccca9c', 'be1e7b6b-3916-50be-b097-abc42b65dbe7', 'fixture', TIMESTAMPTZ '2026-08-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('cebd1e3b-64e2-5142-9c3a-3173a9b9aa98', 'cc7d76d8-cba3-5585-90d2-22e0e89d5094', 'ExponentPushToken[cebd1e3b]', 'ios', TIMESTAMPTZ '2026-08-05 08:00:00+00');
INSERT INTO messages VALUES ('49e473d8-7d4a-5073-964f-e282c1aa940d', '5a29e0d6-06d2-53d2-a99b-2c760b38565e', '6eef59f7-0b84-5184-9bc4-1af058f99224', 'fixture', TIMESTAMPTZ '2026-08-10 12:00:00+00');
INSERT INTO blocks VALUES ('fd17e0e8-c084-528b-977b-c31fe3cf9af3', 'd374dd16-da8d-5f5e-84d7-8921de9d5641', '35252ae5-d52e-5ac6-8440-10156b8b86c8', TIMESTAMPTZ '2026-08-12 05:00:00+00');
INSERT INTO reports VALUES ('e9319db5-c39e-5d34-b3e6-44fb34d9f92d', 'ffeab1d1-17d1-520e-a8aa-2f0ea300cc91', 'fbe93022-5b27-58d0-a369-49de612bb3f5', 'other', TIMESTAMPTZ '2026-08-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('b6941be2-3380-5548-8f51-d8847b8d6359', '3fa635d5-c12f-559f-aeeb-46cc32e875b3', 'primary', TIMESTAMPTZ '2026-08-20 07:00:00+00');
INSERT INTO messages VALUES ('34972cd0-fd7d-56c9-a616-0b7a7696053b', 'e8a717bf-952d-5e01-809b-72f9317bd4b7', '1e2fb28c-dd82-5588-9d10-c596995a6eaa', 'fixture', TIMESTAMPTZ '2026-08-24 21:45:00+00');
INSERT INTO messages VALUES ('df15e252-168a-5fef-9a56-3f4a49a9c07f', '4257954d-a1ca-533f-b570-24590b811305', 'b4255fd2-3d0f-57ca-8f38-4b98e2330201', 'fixture', TIMESTAMPTZ '2026-09-03 03:05:00+00');
INSERT INTO push_tokens VALUES ('5a7156c5-b13c-5d3b-85a3-3eb7824d2f96', 'f5140dbf-e8ff-55b6-9ff5-4a4601fe095b', 'ExponentPushToken[5a7156c5]', 'ios', TIMESTAMPTZ '2026-09-05 08:00:00+00');
INSERT INTO messages VALUES ('6d021b42-dfe1-537a-a016-03d23e5623da', '0885a27a-30e2-5205-8ffc-183b8c608449', 'a0ff0b22-0e68-5280-9723-79becf27e9e1', 'fixture', TIMESTAMPTZ '2026-09-10 12:00:00+00');
INSERT INTO blocks VALUES ('1be85e39-b7c6-5b46-b4c1-38dfe8ac6915', '5f3885bf-0565-5be9-be4f-8259b3036823', '0bd5bc90-4a4b-5b75-8110-7bdd33573385', TIMESTAMPTZ '2026-09-12 05:00:00+00');
INSERT INTO reports VALUES ('8d895ba1-3544-5a6c-adf6-a0677209ed84', '803147e7-e0c7-54e3-be67-cafec587882d', '054e673d-be10-5774-9019-1c0199c297d9', 'other', TIMESTAMPTZ '2026-09-12 05:10:00+00');
INSERT INTO google_calendar_tokens VALUES ('53e96b23-76ec-50d9-972b-ffd4e22999ba', 'd06de7f8-b8a2-5d65-97fc-a6539dcfd925', 'primary', TIMESTAMPTZ '2026-09-20 07:00:00+00');
INSERT INTO messages VALUES ('3320f580-03b1-5285-992d-325bf4341abc', '5768ecee-51c3-5d36-a9f5-b38003291cd4', '07bb6b84-4c45-589e-8d40-e97de4f658f3', 'fixture', TIMESTAMPTZ '2026-09-24 21:45:00+00');
\connect - postgres
RESET TIME ZONE;
DO $$BEGIN IF current_setting('TimeZone') <> 'UTC' THEN RAISE EXCEPTION 'writer zone is %', current_setting('TimeZone'); END IF; END$$;  -- writer: role postgres, session TimeZone UTC
ALTER ROLE fx_api IN DATABASE r6_g RESET timezone;
