#!/usr/bin/env python3
"""Local SportsGang QA environment for hands-on testing.

    npm run qa:up [-- --mode simulator|device] [-- --no-open]
    npm run qa:status
    npm run qa:seed
    npm run qa:open
    npm run qa:restart               # restart API + Metro on the current code
    npm run qa:down
    npm run qa:reset -- --yes        # QA database only: drop, migrate, reseed

Everything this tool owns is local and identifiable:
  * Docker Compose project `sportsgang-qa` (scripts/qa/compose.qa.yml):
    PostgreSQL with the named volume `sportsgang-qa_pgdata` and Redis, both
    bound to 127.0.0.1. `down` stops them and keeps the volume.
  * The API (uvicorn) and Metro (Expo, for Expo Go) processes it starts,
    tracked by PID in .qa/state.json. `status`/`down` only touch those PIDs.
  * .qa/ (git-ignored): config.env (ports, generated secrets), credentials
    and fixture manifest from the seeder, cached tokens, logs.

The API always runs with APP_ENV=local, a generated SECRET_KEY, blank
provider keys and this stack's database; the mobile app is started with
EXPO_PUBLIC_API_URL pointing at this API (127.0.0.1 for the simulator, the
Mac's private LAN address for a physical phone), and `status` reads the URL
back from the manifest Metro actually serves.

Stdlib only (the seeder runs inside apps/api's uv environment).
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import os
import secrets
import signal
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
QA = ROOT / ".qa"
CONFIG = QA / "config.env"
STATE = QA / "state.json"
LOGS = QA / "logs"
COMPOSE = ["docker", "compose", "-p", "sportsgang-qa", "-f", str(ROOT / "scripts/qa/compose.qa.yml")]
API_DIR = ROOT / "apps/api"
MOBILE_DIR = ROOT / "apps/mobile"
DEFAULT_PORTS = {"QA_API_PORT": 8130, "QA_METRO_PORT": 8190, "QA_PG_PORT": 55470, "QA_REDIS_PORT": 56470}
DB_NAME = "sportsgang_qa"


# ─── small helpers ──────────────────────────────────────────────────────────


def say(msg: str) -> None:
    print(f"[qa] {msg}", flush=True)


def fail(msg: str, code: int = 1) -> None:
    print(f"[qa] ERROR: {msg}", file=sys.stderr, flush=True)
    sys.exit(code)


def run(cmd: list[str], cwd: Path = ROOT, env: dict | None = None, check: bool = True, capture: bool = False):
    result = subprocess.run(cmd, cwd=cwd, env=env, text=True, capture_output=capture)
    if check and result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()[-800:] if capture else ""
        fail(f"command failed ({result.returncode}): {' '.join(cmd)}\n{detail}")
    return result


def private(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    os.chmod(path, 0o600)


def read_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if path.exists():
        for line in path.read_text().splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                k, v = line.split("=", 1)
                out[k.strip()] = v.strip()
    return out


def write_env(values: dict[str, str]) -> None:
    lines = ["# Generated by scripts/qa/qa.py — local QA only, never commit."]
    lines += [f"{k}={v}" for k, v in values.items()]
    private(CONFIG, "\n".join(lines) + "\n")


def load_state() -> dict:
    return json.loads(STATE.read_text()) if STATE.exists() else {}


def save_state(state: dict) -> None:
    private(STATE, json.dumps(state, indent=2) + "\n")


def port_free(port: int, host: str = "127.0.0.1") -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            s.bind((host, port))
        except OSError:
            return False
    # Also refuse ports something answers on (e.g. bound to another interface).
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.3)
        return s.connect_ex(("127.0.0.1", port)) != 0


def http_get(url: str, headers: dict | None = None, timeout: float = 5.0) -> tuple[int, str]:
    req = urllib.request.Request(url, headers=headers or {})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, resp.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode("utf-8", "replace")
    except (urllib.error.URLError, OSError) as e:
        return 0, str(e)


def lan_ip() -> str | None:
    for iface in ("en0", "en1"):
        r = subprocess.run(["ipconfig", "getifaddr", iface], capture_output=True, text=True)
        ip = r.stdout.strip()
        if ip:
            try:
                if ipaddress.ip_address(ip).is_private:
                    return ip
            except ValueError:
                pass
    return None


def source_sha() -> str:
    r = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True)
    return r.stdout.strip()


# ─── configuration ──────────────────────────────────────────────────────────


def ensure_config() -> dict[str, str]:
    cfg = read_env(CONFIG)
    changed = False
    for key, default in DEFAULT_PORTS.items():
        if key not in cfg:
            cfg[key] = str(default)
            changed = True
    if "QA_PG_PASSWORD" not in cfg:
        cfg["QA_PG_PASSWORD"] = secrets.token_hex(16)
        changed = True
    if "QA_SECRET_KEY" not in cfg:
        cfg["QA_SECRET_KEY"] = secrets.token_hex(32)
        changed = True
    if changed or not CONFIG.exists():
        write_env(cfg)
    os.chmod(QA, 0o700)
    return cfg


def pick_port(cfg: dict[str, str], key: str) -> None:
    """Keep the configured port when free; otherwise move to the next free one."""
    port = int(cfg[key])
    if port_free(port):
        return
    for candidate in range(port + 1, port + 40):
        if port_free(candidate):
            say(f"port {port} for {key} is used by something else; using {candidate}")
            cfg[key] = str(candidate)
            write_env(cfg)
            return
    fail(f"no free port near {port} for {key}")


def api_env(cfg: dict[str, str]) -> dict[str, str]:
    """Explicit environment for the API: nothing inherited except PATH/HOME/locale."""
    base = {k: os.environ[k] for k in ("PATH", "HOME", "LANG", "LC_ALL", "USER", "TMPDIR") if k in os.environ}
    pw = cfg["QA_PG_PASSWORD"]
    return {
        **base,
        "APP_ENV": "local",
        "SECRET_KEY": cfg["QA_SECRET_KEY"],
        "POSTGRES_URL": f"postgresql://sportsgang_qa:{pw}@127.0.0.1:{cfg['QA_PG_PORT']}/{DB_NAME}",
        "REDIS_URL": f"redis://127.0.0.1:{cfg['QA_REDIS_PORT']}/0",
        "MEDIA_ROOT": str(QA / "media"),
        "CORS_ORIGINS": "",
        # Providers stay off in the QA stack.
        "GOOGLE_PLACES_API_KEY": "",
        "GOOGLE_CLIENT_ID": "",
        "GOOGLE_CLIENT_SECRET": "",
        "APPLE_CLIENT_ID": "",
        "APPLE_TEAM_ID": "",
        "APPLE_KEY_ID": "",
        "APPLE_PRIVATE_KEY": "",
        "FIELD_ENCRYPTION_KEY": "",
        "INTERNAL_API_TOKEN": "",
        "EXPO_PUSH_URL": "http://127.0.0.1:9/disabled-in-qa",
        "PYTHONUNBUFFERED": "1",
    }


def api_host(mode: str) -> str:
    if mode == "simulator":
        return "127.0.0.1"
    ip = lan_ip()
    if not ip:
        fail("no private LAN address found for device mode (is Wi-Fi connected?)")
    return ip


def mobile_api_url(cfg: dict[str, str], mode: str) -> str:
    return f"http://{api_host(mode)}:{cfg['QA_API_PORT']}"


# ─── process ownership ──────────────────────────────────────────────────────


def proc_alive(entry: dict | None, marker: str) -> bool:
    if not entry:
        return False
    pid = entry.get("pid")
    try:
        os.kill(pid, 0)
    except (OSError, TypeError):
        return False
    r = subprocess.run(["ps", "-o", "command=", "-p", str(pid)], capture_output=True, text=True)
    return marker in r.stdout


def start_detached(name: str, cmd: list[str], cwd: Path, env: dict) -> dict:
    LOGS.mkdir(parents=True, exist_ok=True)
    log = open(LOGS / f"{name}.log", "a")
    log.write(f"\n===== {datetime.now(timezone.utc).isoformat()} {' '.join(cmd)}\n")
    log.flush()
    # A new session keeps the process alive after this terminal (or agent) exits.
    proc = subprocess.Popen(cmd, cwd=cwd, env=env, stdout=log, stderr=subprocess.STDOUT,
                            stdin=subprocess.DEVNULL, start_new_session=True)
    return {"pid": proc.pid, "cmd": " ".join(cmd), "cwd": str(cwd), "log": str(LOGS / f"{name}.log"),
            "started_at": datetime.now(timezone.utc).isoformat(timespec="seconds")}


def stop_proc(entry: dict | None, marker: str, name: str) -> None:
    if not proc_alive(entry, marker):
        return
    pid = entry["pid"]
    try:
        os.killpg(os.getpgid(pid), signal.SIGTERM)
    except OSError:
        os.kill(pid, signal.SIGTERM)
    for _ in range(40):
        if not proc_alive(entry, marker):
            say(f"stopped {name} (pid {pid})")
            return
        time.sleep(0.25)
    try:
        os.killpg(os.getpgid(pid), signal.SIGKILL)
    except OSError:
        pass
    say(f"killed {name} (pid {pid})")


def api_marker(cfg: dict[str, str]) -> str:
    return f"--port {cfg['QA_API_PORT']}"


def metro_marker(cfg: dict[str, str]) -> str:
    return f"--port {cfg['QA_METRO_PORT']}"


# ─── stack steps ────────────────────────────────────────────────────────────


def compose(*args: str, capture: bool = False, check: bool = True):
    return run([*COMPOSE, "--env-file", str(CONFIG), *args], capture=capture, check=check)


def containers_running() -> bool:
    r = compose("ps", "--status", "running", "-q", capture=True, check=False)
    return len([x for x in r.stdout.split() if x]) >= 2


def ensure_containers(cfg: dict[str, str]) -> bool:
    if containers_running():
        return False
    pick_port(cfg, "QA_PG_PORT")
    pick_port(cfg, "QA_REDIS_PORT")
    say("starting PostgreSQL and Redis (project sportsgang-qa)")
    compose("up", "-d", "--wait")
    return True


def migrate(cfg: dict[str, str]) -> None:
    run(["uv", "run", "--frozen", "alembic", "upgrade", "head"], cwd=API_DIR, env=api_env(cfg), capture=True)
    current = run(["uv", "run", "--frozen", "alembic", "current"], cwd=API_DIR, env=api_env(cfg), capture=True)
    say(f"database {DB_NAME} at migration {current.stdout.strip() or '?'}")


def wait_http(url: str, ok, seconds: float, what: str) -> str:
    deadline = time.time() + seconds
    last = ""
    while time.time() < deadline:
        code, body = http_get(url)
        if code and ok(code, body):
            return body
        last = f"{code} {body[:120]}"
        time.sleep(1)
    fail(f"{what} not ready at {url} ({last})")
    return ""


def ensure_api(cfg: dict[str, str], state: dict, mode: str, started: list[str]) -> None:
    host = api_host(mode)
    entry = state.get("api")
    if proc_alive(entry, api_marker(cfg)) and entry.get("host") == host:
        return
    stop_proc(entry, api_marker(cfg), "api")
    pick_port(cfg, "QA_API_PORT")
    cmd = ["uv", "run", "--frozen", "uvicorn", "app.main:app", "--host", host, "--port", cfg["QA_API_PORT"]]
    entry = start_detached("api", cmd, API_DIR, api_env(cfg))
    entry["host"] = host
    state["api"] = entry
    save_state(state)
    started.append("api")  # before waiting, so a failed start is cleaned up
    wait_http(f"http://{host}:{cfg['QA_API_PORT']}/health",
              lambda c, b: c == 200 and '"db":"ok"' in b.replace(" ", ""), 60, "API")
    say(f"API up at http://{host}:{cfg['QA_API_PORT']} (pid {entry['pid']})")


def metro_env(cfg: dict[str, str], mode: str) -> dict[str, str]:
    env = {k: v for k, v in os.environ.items() if not k.startswith("EXPO_PUBLIC_")}
    env.update({
        "EXPO_PUBLIC_API_URL": mobile_api_url(cfg, mode),
        "APP_ENV": "local",
        "CI": "1",  # non-interactive Metro (no TTY when detached)
        "EXPO_OFFLINE": "1",  # no Expo account / network calls
        "EXPO_NO_TELEMETRY": "1",
    })
    return env


def ensure_metro(cfg: dict[str, str], state: dict, mode: str, started: list[str]) -> None:
    entry = state.get("metro")
    if proc_alive(entry, metro_marker(cfg)) and entry.get("mode") == mode:
        return
    stop_proc(entry, metro_marker(cfg), "metro")
    pick_port(cfg, "QA_METRO_PORT")
    host_flag = "--localhost" if mode == "simulator" else "--lan"
    cmd = ["npx", "--no-install", "expo", "start", host_flag, "--port", cfg["QA_METRO_PORT"]]
    entry = start_detached("metro", cmd, MOBILE_DIR, metro_env(cfg, mode))
    entry["mode"] = mode
    state["metro"] = entry
    save_state(state)
    started.append("metro")
    wait_http(f"http://127.0.0.1:{cfg['QA_METRO_PORT']}/status",
              lambda c, b: "packager-status:running" in b, 180, "Metro")
    say(f"Metro up on port {cfg['QA_METRO_PORT']} (pid {entry['pid']})")


def runtime_url(cfg: dict[str, str], mode: str) -> str:
    host = "127.0.0.1" if mode == "simulator" else (lan_ip() or "127.0.0.1")
    return f"exp://{host}:{cfg['QA_METRO_PORT']}"


def served_api_url(cfg: dict[str, str]) -> str | None:
    """apiUrl from the manifest Metro serves to Expo Go (what the app will use)."""
    code, body = http_get(
        f"http://127.0.0.1:{cfg['QA_METRO_PORT']}/",
        headers={"expo-platform": "ios", "accept": "application/expo+json,application/json"},
        timeout=60,
    )
    if code != 200:
        return None
    try:
        manifest = json.loads(body)
    except json.JSONDecodeError:
        return None
    extra = (manifest.get("extra") or {}).get("expoClient", {}).get("extra") or manifest.get("extra") or {}
    return extra.get("apiUrl")


def seed(cfg: dict[str, str], mode: str) -> None:
    env = api_env(cfg)
    env["QA_API_URL"] = f"http://{api_host(mode)}:{cfg['QA_API_PORT']}"
    env["QA_DIR"] = str(QA)
    say("seeding demo fixtures (idempotent; a first run waits out the real register/login rate limits)")
    r = subprocess.run(["uv", "run", "--frozen", "python", str(ROOT / "scripts/qa/seed_qa.py")], cwd=API_DIR, env=env)
    if r.returncode != 0:
        fail("seeding failed (see output above)")


def authenticated_read(cfg: dict[str, str], mode: str) -> tuple[bool, str]:
    tokens_path = QA / "tokens.json"
    if not tokens_path.exists():
        return False, "no cached QA token (run qa:seed)"
    token = json.loads(tokens_path.read_text()).get("alice", {}).get("token")
    base = f"http://{api_host(mode)}:{cfg['QA_API_PORT']}"
    code, body = http_get(f"{base}/auth/me", {"Authorization": f"Bearer {token}"})
    if code != 200:
        return False, f"/auth/me → {code}"
    as_of = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    code, body = http_get(f"{base}/events?mine=true&segment=past&as_of={as_of}&limit=1",
                          {"Authorization": f"Bearer {token}"})
    if code != 200:
        return False, f"/events → {code}"
    return True, f"QA Alice signed in; {json.loads(body)['total']} past sessions in her My Plans"


def fixture_counts() -> dict[str, object]:
    sql = (
        "select (select count(*) from users where email like 'qa.%@example.com'),"
        " (select count(*) from events where title like 'QA %'),"
        " (select count(*) from bookings b join users u on u.id=b.proposer_id where u.email like 'qa.%@example.com'),"
        " (select count(*) from events where title like 'QA history run%'),"
        " (select version_num from alembic_version)"
    )
    r = compose("exec", "-T", "postgres", "psql", "-U", "sportsgang_qa", "-d", DB_NAME, "-tA", "-c", sql,
                capture=True, check=False)
    parts = r.stdout.strip().split("|")
    if len(parts) != 5:
        return {}
    return {"qa_users": int(parts[0]), "qa_sessions": int(parts[1]), "qa_bookings": int(parts[2]),
            "qa_history_sessions": int(parts[3]), "migration": parts[4]}


def open_simulators(cfg: dict[str, str]) -> list[str]:
    r = subprocess.run(["xcrun", "simctl", "list", "devices", "booted", "-j"], capture_output=True, text=True)
    if r.returncode != 0:
        return []
    opened = []
    for devices in json.loads(r.stdout).get("devices", {}).values():
        for d in devices:
            if d.get("state") == "Booted" and "iPhone" in d.get("name", ""):
                # Expo Go keeps the previous JS bundle when it is already open,
                # so quit it first; sign-in survives (it is stored on device).
                subprocess.run(["xcrun", "simctl", "terminate", d["udid"], "host.exp.Exponent"],
                               capture_output=True)
                subprocess.run(["xcrun", "simctl", "openurl", d["udid"], runtime_url(cfg, "simulator")],
                               capture_output=True)
                opened.append(f"{d['name']} ({d['udid']})")
    return opened


def print_qr(url: str) -> None:
    node = "const q=require('qrcode-terminal');q.generate(process.argv[1],{small:true},s=>console.log(s));"
    subprocess.run(["node", "-e", node, url], cwd=ROOT, check=False)


# ─── commands ───────────────────────────────────────────────────────────────


def cmd_up(args) -> None:
    cfg = ensure_config()
    state = load_state()
    mode = args.mode or state.get("mode") or "simulator"
    started: list[str] = []
    try:
        if ensure_containers(cfg):
            started.append("containers")
        migrate(cfg)
        ensure_api(cfg, state, mode, started)
        state["mode"] = mode
        save_state(state)
        if not args.no_seed:
            seed(cfg, mode)
        ensure_metro(cfg, state, mode, started)
    except SystemExit:
        # Clean up only what this invocation started; never the volume.
        say("startup failed; stopping what this run started: " + (", ".join(started) or "nothing"))
        if "metro" in started:
            stop_proc(state.get("metro"), metro_marker(cfg), "metro")
        if "api" in started:
            stop_proc(state.get("api"), api_marker(cfg), "api")
        if "containers" in started:
            compose("stop", check=False)
        raise
    state.update({"mode": mode, "source_sha": source_sha(), "worktree": str(ROOT),
                  "updated_at": datetime.now(timezone.utc).isoformat(timespec="seconds")})
    save_state(state)
    if not status(cfg, state):
        fail("environment is not ready (see status above)")
    if mode == "simulator" and not args.no_open:
        opened = open_simulators(cfg)
        say("opened in: " + (", ".join(opened) if opened else "no booted iPhone simulator found"))
    if mode == "device":
        say(f"On the iPhone (same Wi-Fi), scan this QR or open in Expo Go: {runtime_url(cfg, 'device')}")
        print_qr(runtime_url(cfg, "device"))


def status(cfg: dict[str, str], state: dict) -> bool:
    mode = state.get("mode", "simulator")
    checks: list[tuple[str, bool, str]] = []
    checks.append(("containers", containers_running(), "sportsgang-qa postgres + redis"))
    api_entry = state.get("api") or {}
    api_ok = proc_alive(api_entry, api_marker(cfg))
    host = api_entry.get("host", "127.0.0.1")
    code = http_get(f"http://{host}:{cfg['QA_API_PORT']}/health")[0] if api_ok else 0
    checks.append(("api", api_ok and code == 200,
                   f"pid {api_entry.get('pid')} http://{host}:{cfg['QA_API_PORT']} health={code}"))
    if api_ok:
        good, detail = authenticated_read(cfg, mode)
        checks.append(("auth read", good, detail))
    metro_entry = state.get("metro") or {}
    metro_ok = proc_alive(metro_entry, metro_marker(cfg))
    checks.append(("metro", metro_ok, f"pid {metro_entry.get('pid')} port {cfg['QA_METRO_PORT']} ({mode} mode)"))
    if metro_ok:
        served = served_api_url(cfg)
        expected = mobile_api_url(cfg, mode)
        checks.append(("app API URL", served == expected, f"served {served} (expected {expected})"))
    counts = fixture_counts() if checks[0][1] else {}
    say(f"worktree {ROOT}")
    say(f"source {source_sha()[:12]} (stack last started from {str(state.get('source_sha', ''))[:12]})")
    for name, ok, detail in checks:
        print(f"   {'OK ' if ok else 'BAD'} {name:12} {detail}")
    if counts:
        print(f"   fixtures     {counts}")
    print(f"   app URL      {runtime_url(cfg, mode)}")
    print(f"   credentials  {QA / 'credentials.json'}")
    print(f"   manifest     {QA / 'manifest.json'}")
    print(f"   logs         {LOGS}")
    return all(ok for _, ok, _ in checks)


def cmd_status(args) -> None:
    cfg = ensure_config()
    state = load_state()
    ok = status(cfg, state)
    if args.qr:
        print_qr(runtime_url(cfg, state.get("mode", "simulator")))
    if not ok:
        sys.exit(1)


def cmd_seed(args) -> None:
    cfg = ensure_config()
    state = load_state()
    if not proc_alive(state.get("api"), api_marker(cfg)):
        fail("API is not running; use `npm run qa:up`")
    seed(cfg, state.get("mode", "simulator"))


def cmd_open(args) -> None:
    cfg = ensure_config()
    opened = open_simulators(cfg)
    say("opened in: " + (", ".join(opened) if opened else "no booted iPhone simulator found"))


def cmd_down(args) -> None:
    cfg = ensure_config()
    state = load_state()
    stop_proc(state.get("metro"), metro_marker(cfg), "metro")
    stop_proc(state.get("api"), api_marker(cfg), "api")
    if containers_running():
        compose("stop")
        say("containers stopped; demo data kept in volume sportsgang-qa_pgdata")
    state.pop("api", None)
    state.pop("metro", None)
    save_state(state)


def cmd_stop_api(args) -> None:
    """Stop only the QA API so the app can be tested against an unreachable server."""
    cfg = ensure_config()
    state = load_state()
    stop_proc(state.get("api"), api_marker(cfg), "api")
    state.pop("api", None)
    save_state(state)
    say("API stopped; Metro, containers and data untouched. Bring it back with: npm run qa:up -- --no-open --no-seed")


def cmd_restart(args) -> None:
    """Restart the API and Metro (e.g. after pulling new code); data is untouched."""
    cfg = ensure_config()
    state = load_state()
    stop_proc(state.get("metro"), metro_marker(cfg), "metro")
    stop_proc(state.get("api"), api_marker(cfg), "api")
    cmd_up(argparse.Namespace(mode=args.mode or state.get("mode"), no_open=args.no_open, no_seed=True))


def cmd_reset(args) -> None:
    if not args.yes:
        fail("reset drops and recreates ONLY the sportsgang_qa database; re-run with `-- --yes`")
    cfg = ensure_config()
    state = load_state()
    if not containers_running():
        fail("QA containers are not running; use `npm run qa:up` first")
    say("resetting the sportsgang_qa database (QA stack only)")
    stop_proc(state.get("api"), api_marker(cfg), "api")
    for sql in (
        f"SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='{DB_NAME}' AND pid<>pg_backend_pid()",
        f"DROP DATABASE IF EXISTS {DB_NAME}",
        f"CREATE DATABASE {DB_NAME} OWNER sportsgang_qa",
    ):
        compose("exec", "-T", "postgres", "psql", "-U", "sportsgang_qa", "-d", "postgres", "-c", sql, capture=True)
    for name in ("manifest.json", "tokens.json"):
        (QA / name).unlink(missing_ok=True)
    compose("exec", "-T", "redis", "redis-cli", "FLUSHDB", capture=True)
    cmd_up(argparse.Namespace(mode=state.get("mode"), no_open=True, no_seed=False))


def main() -> None:
    parser = argparse.ArgumentParser(prog="qa", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    up = sub.add_parser("up", help="start (or recover) the QA stack, seed, and open the app")
    up.add_argument("--mode", choices=["simulator", "device"], help="default: last mode, else simulator")
    up.add_argument("--no-open", action="store_true", help="do not open the app in booted simulators")
    up.add_argument("--no-seed", action="store_true", help="skip the idempotent seed step")
    up.set_defaults(func=cmd_up)
    st = sub.add_parser("status", help="show health, ownership, app API URL and fixture counts")
    st.add_argument("--qr", action="store_true", help="also print a QR code for the Expo Go URL")
    st.set_defaults(func=cmd_status)
    sub.add_parser("seed", help="create any missing demo fixtures").set_defaults(func=cmd_seed)
    sub.add_parser("open", help="open the app in booted iPhone simulators").set_defaults(func=cmd_open)
    sub.add_parser("down", help="stop API, Metro and containers; keep demo data").set_defaults(func=cmd_down)
    sub.add_parser("stop-api", help="stop only the API (offline/retry testing)").set_defaults(func=cmd_stop_api)
    rt = sub.add_parser("restart", help="restart API and Metro on the current code; keep data")
    rt.add_argument("--mode", choices=["simulator", "device"])
    rt.add_argument("--no-open", action="store_true")
    rt.set_defaults(func=cmd_restart)
    rs = sub.add_parser("reset", help="drop + recreate the QA database only, then reseed")
    rs.add_argument("--yes", action="store_true")
    rs.set_defaults(func=cmd_reset)
    args = parser.parse_args()
    QA.mkdir(exist_ok=True)
    args.func(args)


if __name__ == "__main__":
    main()
